services:
  web:
    image: ghcr.io/clagomess/docker-php-5.6
    network_mode: "bridge"
    ports:
      - "8000:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    environment:
      XDEBUG_REMOTE_ENABLE: 1
      XDEBUG_REMOTE_HOST: host.docker.internal
      XDEBUG_REMOTE_PORT: 9000
