name: release
on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build -t ghcr.io/clagomess/docker-php-5.6 -f Dockerfile .

      - name: Push GHCR
        run: |
          docker tag ghcr.io/clagomess/docker-php-5.6 ghcr.io/clagomess/docker-php-5.6:${{github.run_number}}
          docker push ghcr.io/clagomess/docker-php-5.6:${{github.run_number}}
          docker push ghcr.io/clagomess/docker-php-5.6:latest

      - name: Push DockerHub
        run: |
          docker tag ghcr.io/clagomess/docker-php-5.6 docker.io/clagomess/docker-php-5.6:${{github.run_number}}
          docker tag ghcr.io/clagomess/docker-php-5.6 docker.io/clagomess/docker-php-5.6:latest
          docker push docker.io/clagomess/docker-php-5.6:${{github.run_number}}
          docker push docker.io/clagomess/docker-php-5.6:latest
          
