name: release
on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/clagomess/docker-php-5.6 -f Dockerfile .
          docker tag ghcr.io/clagomess/docker-php-5.6 ghcr.io/clagomess/docker-php-5.6:${{github.run_number}}
          docker push ghcr.io/clagomess/docker-php-5.6:${{github.run_number}}
          docker push ghcr.io/clagomess/docker-php-5.6:latest
